@EncryptedFileDropAPI_HostAddress = https://localhost:7090

POST {{EncryptedFileDropAPI_HostAddress}}/api/user/register
Content-Type: application/json

{
  "name": "GabrielAlexander",
  "userName": "gabeamv",
  "passwordHash": "test123"
}

###

POST {{EncryptedFileDropAPI_HostAddress}}/api/user/login
Content-Type: application/json

{
  "userName": "gabeamv",
  "passwordHash": "test123"
}

###

POST {{EncryptedFileDropAPI_HostAddress}}/api/user/register
Content-Type: application/json

{
  //User
}

###
